apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ui
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis-ui
  template:
    metadata:
      labels:
        app: redis-ui
    spec:
      containers:
      - name: redis-ui
        imagePullPolicy: Always
        # image: distrokid/tasks-server:tomcat-latest
        image: rediscommander/redis-commander:latest
        env:
          - name: ENV
            value: local
          - name: APP
            value: redis-commander
          - name: MACHINE_NAME
            value: redis-ui
          - name: REDIS_HOSTS
            value: local:redis-server-local:6379
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ui-service
spec:
  selector:
    app: redis-ui
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081