version: '3'
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - password=${LOCAL_PASSWORD:-password}
    ports:
      - "9999:8888"
    volumes:
      - '${PWD}/www:/var/www'
    environment:
      - REDIS_SERVER_LOCAL_SERVICE_HOST=redis
      - REDIS_SERVER_LOCAL_SERVICE_PORT=6379

  redis:
    image:  redis:6.2.5
    expose:
      - 6379
    
  redis_ui:
    image: rediscommander/redis-commander:latest
    ports: 
      - 9091:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
      - ENV=local