apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-local
spec:
  # progressDeadlineSeconds: 600
  replicas: 1
  # revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis-server-local
  template:
    metadata:
      labels:
        app: redis-server-local
    spec:
      containers:
      - name: redis-server-local
        image: redis:latest
        imagePullPolicy: Always
        env:
          - name: ENV
            value: local
          - name: APP
            value: redis
          - name: MACHINE_NAME
            value: redis-server-local
            
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server-local
spec:
  selector:
    app: redis-server-local
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379